stages:
- stage: Build
  jobs:
  - job: Build
    pool: 'nikhilku'
    steps:
    - script: echo 'Build'

- stage: PPE
  jobs:
  - job: Test
    pool: 'nikhilku'
    steps:
    - script: echo 'Hosted'
    - task: NuGetToolInstaller@0
  - deployment: DeployPPE
    environment: Nikhil-Env
    pool: 'nikhilku'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello, world!
            displayName: 'Run a one-line script'

- stage: Prod
  jobs:
  - job: DeployProd
    pool: 'nikhilku'
    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: 'Azure Deployment:Start action on abhishe-RG'
      inputs:
        azureSubscription: NikhilRMDev
        action: Start
        resourceGroupName: 'abhishe-RG'
