stages:
- stage: Build
  jobs:
  - job: Build
    pool: 'Default'
    steps:
    - script: echo 'Build'

- stage: PPE
  jobs:
  - job: Test
    pool: 'Default'
    steps:
    - script: echo 'Default'
    - task: NuGetToolInstaller@0
  - deployment: DeployPPE
    environment: Nikhil-Env
    pool: 'Default'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello, world!
            displayName: 'Run a one-line script'

- stage: Prod
  jobs:
  - job: DeployProd
    pool: 'Default'
    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: 'Azure Deployment:Start action on Project1-app'
      inputs:
        azureSubscription: RMDev
        action: Start
        resourceGroupName: 'aafn1'
